feat(blog): new entry
ispp-2324-ocial/landing-page pull request #23
Opened 2024-03-12 20:53 UTC by AitorRD

Fixes #22

2024-03-17 16:13 UTC, ferferga requested changes
Dos detalles pequeños

2024-03-17 16:13 UTC, ferferga commented on src/content/blog/inauguration.md
> +title: "Inauguramos la Landing Page de la organización."
```suggestion
title: "Inauguramos la página principal de nuestra empresa."
```

No mezclemos español con inglés

2024-03-17 16:13 UTC, ferferga commented on src/pages/about.astro
> +        a la hora de realizar este proyecto.
"Y las principales funciones que desempeñarán" queda mucho más profesional

2024-03-17 19:22 UTC, AitorRD commented on src/pages/about.astro
> +        a la hora de realizar este proyecto.
Cierto, hechos esos dos cambios en las expresiones en este [commit](https://github.com/ispp-2324-ocial/landing-page/pull/23/commits/fe8137055c9e0d01cacd1bacc5f902872916398b)

2024-03-18 09:50 UTC, adrrf approved these changes
Todo ok

2024-03-18 15:01 UTC, ferferga approved these changes

2024-03-18 15:01 UTC, merged