feat: añadidos campos sobre nosotros y contacto #5
ispp-2324-ocial/landing-page pull request #6
Opened 2024-02-21 19:46 UTC by adrrf

Se han añadido la información sobre el equipo de desarrollo (nombres, roles e imagenes) y la información sobre contacto.

2024-02-21 22:49 UTC, ferferga requested changes
No se sigue conventional commits

2024-02-22 09:14 UTC, AitorRD requested changes
Tanto este commi ( d591caefbc6b967f0ad0dd9d5121519b688520c4 ) como este commit ( a0b6aa3d6eb037b38af4b727591dace12f285a69 ) no cumple el conventional commits

2024-02-22 09:57 UTC, AitorRD approved these changes

2024-02-23 08:53 UTC, ferferga approved these changes

2024-02-23 08:54 UTC, merged