feat: create a new blog and first article
ispp-2324-ocial/landing-page pull request #9
Opened 2024-02-24 11:22 UTC by AitorRD

Link a la issue -> #4

2024-02-24 12:46 UTC, adrrf requested changes
Veo todo en orden, para la proxima añadir el scope y cuidado con usar feat en vez de fix (ejemplo ultimo commit)

2024-02-24 14:02 UTC, AitorRD commented
> Veo todo en orden, para la proxima añadir el scope y cuidado con usar feat en vez de fix (ejemplo ultimo commit)

me di cuenta tarde que me equivoque con el nombre del commit y con el rebase no me dejaba cambiarlo ahora miro la reunión de fernando como lo hizo pa cambiarlo y lo hago

2024-02-24 15:07 UTC, Ramguerom commented
Creo recordar que con git rebase -i (te salía una terminal o algo así), y ahi podías con reword cambiar el nombre del commit

2024-02-25 21:03 UTC, adrrf reviewed
Ya sí, todo bien

2024-02-25 21:04 UTC, adrrf approved these changes
que no he aprobado, srry

2024-02-26 10:20 UTC, Ramguerom approved these changes
Veo todo correcto

2024-02-26 10:22 UTC, merged